services:
  acemq_server:
    container_name: acemq_server
    environment:
      ACE_SERVER_NAME: ACEMQ_SERVER
      USE_QMGR: 'true'
      MQ_QMGR_NAME: QMGR
      LOG_FORMAT: 'json'
      LICENSE: accept
      LANG: es
      MQ_ENABLE_METRICS: 'true'
      ACE_ENABLE_METRICS: 'true'
    image: ibmcom/ace-mq:latest
    privileged: 'true'
    ports:
    - 7600:7600
    - 7680:7680
    - 7800:7800
    - 7843:7843
    - 1414:1414
    - 2800:2800
    - 2801:2801
    - 2803:2803
    volumes:
      - ./aceuser/initial-config:/home/aceuser/initial-config
      - ./aceuser/ace-server:/home/aceuser/ace-server
      - ./volumens/mqm/mnt:/mnt/mqm
version: '3'
